"""Initial migration

Revision ID: a1b2c3d4e5f6
Revises: 
Create Date: 2025-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('configurazione',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('lunghezza_tunnel_m', sa.Float(), nullable=True),
        sa.Column('velocita_default', sa.Float(), nullable=True),
        sa.Column('velocita_min', sa.Float(), nullable=True),
        sa.Column('velocita_max', sa.Float(), nullable=True),
        sa.Column('capacita_termica_max_kg', sa.Float(), nullable=True),
        sa.Column('costo_orario_esercizio', sa.Float(), nullable=True),
        sa.Column('costo_manodopera_ora', sa.Float(), nullable=True),
        sa.Column('costo_centro_orario', sa.Float(), nullable=True),
        sa.Column('costo_kwh', sa.Float(), nullable=True),
        sa.Column('peso_specifico_vernice', sa.Float(), nullable=True),
        sa.Column('efficienza_applicazione', sa.Float(), nullable=True),
        sa.Column('spessore_default_micron', sa.Integer(), nullable=True),
        sa.Column('tempo_aggancio_min', sa.Float(), nullable=True),
        sa.Column('tempo_aggancio_medio_min', sa.Float(), nullable=True),
        sa.Column('tempo_aggancio_complesso_min', sa.Float(), nullable=True),
        sa.Column('netpro_api_url', sa.String(length=200), nullable=True),
        sa.Column('netpro_api_key', sa.String(length=100), nullable=True),
        sa.Column('passo_gancio_mm', sa.Float(), nullable=True),
        sa.Column('n_ganci_totali', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('prodotto',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('codice', sa.String(length=50), nullable=False),
        sa.Column('nome', sa.String(length=200), nullable=False),
        sa.Column('descrizione', sa.String(length=200), nullable=True),
        sa.Column('famiglia', sa.String(length=100), nullable=True),
        sa.Column('lunghezza_mm', sa.Float(), nullable=True),
        sa.Column('larghezza_mm', sa.Float(), nullable=True),
        sa.Column('altezza_mm', sa.Float(), nullable=True),
        sa.Column('peso_kg', sa.Float(), nullable=True),
        sa.Column('superficie_m2', sa.Float(), nullable=True),
        sa.Column('passo_gancio_m', sa.Float(), nullable=True),
        sa.Column('densita_gcc', sa.Float(), nullable=True),
        sa.Column('densita_materiale', sa.Float(), nullable=True),
        sa.Column('complessita_aggancio', sa.Integer(), nullable=True),
        sa.Column('file_3d', sa.String(length=300), nullable=True),
        sa.Column('note', sa.Text(), nullable=True),
        sa.Column('costo_standard', sa.Float(), nullable=True),
        sa.Column('tempo_standard_min', sa.Float(), nullable=True),
        sa.Column('n_campioni_standard', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('codice')
    )

    op.create_table('ordine_ordine',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('numero_ordine', sa.String(length=50), nullable=True),
        sa.Column('codice_prodotto', sa.String(length=50), nullable=True),
        sa.Column('quantita', sa.Integer(), nullable=True),
        sa.Column('colore', sa.String(length=50), nullable=True),
        sa.Column('priorita', sa.Integer(), nullable=True),
        sa.Column('data_richiesta', sa.String(length=20), nullable=True),
        sa.Column('stato', sa.String(length=20), nullable=True),
        sa.Column('origine', sa.String(length=20), nullable=True),
        sa.Column('centro_lavoro', sa.String(length=50), nullable=True),
        sa.Column('note', sa.Text(), nullable=True),
        sa.Column('creato_il', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('lotto',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('codice_lotto', sa.String(length=50), nullable=True),
        sa.Column('nome', sa.String(length=100), nullable=True),
        sa.Column('data_produzione', sa.String(length=20), nullable=True),
        sa.Column('stato', sa.String(length=20), nullable=True),
        sa.Column('velocita_catena', sa.Float(), nullable=True),
        sa.Column('operatore', sa.String(length=100), nullable=True),
        sa.Column('note', sa.Text(), nullable=True),
        sa.Column('saturazione_pct', sa.Float(), nullable=True),
        sa.Column('peso_totale_kg', sa.Float(), nullable=True),
        sa.Column('lunghezza_usata_m', sa.Float(), nullable=True),
        sa.Column('lunghezza_occupata_m', sa.Float(), nullable=True),
        sa.Column('tempo_ciclo_min', sa.Float(), nullable=True),
        sa.Column('tempo_totale_min', sa.Float(), nullable=True),
        sa.Column('n_pezzi_totali', sa.Integer(), nullable=True),
        sa.Column('n_ganci_totali', sa.Integer(), nullable=True),
        sa.Column('costo_totale', sa.Float(), nullable=True),
        sa.Column('costo_totale_eur', sa.Float(), nullable=True),
        sa.Column('costo_orario', sa.Float(), nullable=True),
        sa.Column('costo_gancio_eur', sa.Float(), nullable=True),
        sa.Column('sequenza_json', sa.Text(), nullable=True),
        sa.Column('inizio', sa.DateTime(), nullable=True),
        sa.Column('fine', sa.DateTime(), nullable=True),
        sa.Column('Q_R_kJ', sa.Float(), nullable=True),
        sa.Column('Q_a_kJ', sa.Float(), nullable=True),
        sa.Column('Q_f_kJ', sa.Float(), nullable=True),
        sa.Column('Q_d_kJ', sa.Float(), nullable=True),
        sa.Column('P_R_kW', sa.Float(), nullable=True),
        sa.Column('energia_kWh', sa.Float(), nullable=True),
        sa.Column('costo_energia_eur', sa.Float(), nullable=True),
        sa.Column('creato_il', sa.DateTime(), nullable=True),
        sa.Column('completato_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('lotto_item',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('lotto_id', sa.Integer(), nullable=False),
        sa.Column('prodotto_id', sa.Integer(), nullable=True),
        sa.Column('quantita', sa.Integer(), nullable=True),
        sa.Column('zona_assegnata', sa.Integer(), nullable=True),
        sa.Column('posizione_inizio_m', sa.Float(), nullable=True),
        sa.Column('n_ganci_occupati', sa.Integer(), nullable=True),
        sa.Column('costo_materiale_unitario', sa.Float(), nullable=True),
        sa.Column('costo_processo_unitario', sa.Float(), nullable=True),
        sa.Column('costo_manodopera_unitario', sa.Float(), nullable=True),
        sa.Column('costo_termico_unitario', sa.Float(), nullable=True),
        sa.Column('costo_unitario_totale', sa.Float(), nullable=True),
        sa.Column('costo_riga', sa.Float(), nullable=True),
        sa.Column('tempo_unitario_min', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['lotto_id'], ['lotto.id'], ),
        sa.ForeignKeyConstraint(['prodotto_id'], ['prodotto.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('storico_costo',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('prodotto_id', sa.Integer(), nullable=True),
        sa.Column('lotto_id', sa.Integer(), nullable=True),
        sa.Column('data', sa.Date(), nullable=True),
        sa.Column('quantita', sa.Integer(), nullable=True),
        sa.Column('costo_materiale', sa.Float(), nullable=True),
        sa.Column('costo_processo', sa.Float(), nullable=True),
        sa.Column('costo_manodopera', sa.Float(), nullable=True),
        sa.Column('costo_totale', sa.Float(), nullable=True),
        sa.Column('tempo_min', sa.Float(), nullable=True),
        sa.Column('velocita_catena', sa.Float(), nullable=True),
        sa.Column('costo_orario', sa.Float(), nullable=True),
        sa.Column('n_ganci', sa.Integer(), nullable=True),
        sa.Column('costo_termico', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['lotto_id'], ['lotto.id'], ),
        sa.ForeignKeyConstraint(['prodotto_id'], ['prodotto.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('kb_regola',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('prodotto_id', sa.Integer(), nullable=True),
        sa.Column('tipo', sa.String(length=30), nullable=True),
        sa.Column('descrizione', sa.Text(), nullable=True),
        sa.Column('zona_min', sa.Integer(), nullable=True),
        sa.Column('zona_max', sa.Integer(), nullable=True),
        sa.Column('spessore_override_micron', sa.Float(), nullable=True),
        sa.Column('velocita_delta_pct', sa.Float(), nullable=True),
        sa.Column('priorita', sa.Integer(), nullable=True),
        sa.Column('attiva', sa.Boolean(), nullable=True),
        sa.Column('creata_da', sa.String(length=50), nullable=True),
        sa.Column('creata_il', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['prodotto_id'], ['prodotto.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kb_regola')
    op.drop_table('storico_costo')
    op.drop_table('lotto_item')
    op.drop_table('lotto')
    op.drop_table('ordine_ordine')
    op.drop_table('prodotto')
    op.drop_table('configurazione')
    # ### end Alembic commands ###
